### ISSUE TITLE
Provide binary release

### ISSUE THREAD

**Issue by niutech** [marcelmaatkamp/cosmopolitan-love2d#1]
Could you please provide the APE binary release (COM file) of Love2D using Cosmopolitan 1.0 for testing purposes? Thanks!

**Comment by marcelmaatkamp** [comment]
This repo I wanted to try to see if a sdl-llibrary like love2d would even be possible to compile and used with cosmopolitan, but:

`configure: error: LÖVE needs "the POSIX threads library", please install "the POSIX threads library" with development files and try again
`
Seems phreads will not be ported to cosmopolitan and love2d would need to be rewritten to support the native threading with fork()/epol in cosmopolitan, see https://github.com/jart/cosmopolitan/issues/114

_@jart do you plan to expand pthreads support (pthread_t, pthread_mutex_t, pthread_cond_t etc) in Cosmopolitan? _ 

Aswer from @jart:

_Threads is unlikely to happen anytime soon. The multi-process fork() i/o model work pretty well across platforms. There's also epoll which is polyfilled on Windows thanks to wepoll but sadly enough not Mac and BSD. What exactly needs to happen with fflush?_
